version: '3.4'

services:
  taskmanagerapi:
    image: taskmanagerapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
